### ISSUE TITLE
Public?

### ISSUE THREAD

**Issue by nomadism19** [SimonHaas/homeserver#1]
Thank you for this, using it as a template from which to learn has been great. Having said that, I would like to publish my containers to the web but have not been successful in many many attempts. Would you have any insight on how to accomplish this? My domain is registered via Cloudflare, I can access all services locally via A-name but not externally.

**Comment by SimonHaas** [comment]
Thanks for your interest and for reaching out. 

Traditionally running a webserver at home required opening port 80 and 443 on your router and using [dynamic DNS](https://en.wikipedia.org/wiki/Dynamic_DNS).
A better way is to use [cloudflare tunnels](https://www.cloudflare.com/products/tunnel/). I have [added it under services and have written instructions](https://github.com/SimonHaas/homeserver/tree/main/services/cloudflared).

Please let me know if my instructions were helpful and whether or not you were able to publish your containers.
You are welcome to contribute improvements via pull requests.

**Comment by nomadism19** [comment]
Thanks mate, I have used cf tunnels with success.

Separate issue, I am unsure why but I cannot get script.sh working. Have added all appropriate services to the .env. It was working fine prior to the recent services updates, which is why I ask. I’m sure the problem is on my end somewhere, any ideas? Permissions are all correct, including script and.env.
From within homeserver directory I am using command `sudo bash ./script.sh -d`. No errors, command runs successfully but no containers are started. Can you confirm it works on your end?

**Comment by SimonHaas** [comment]
Upsi. I actually changed how the script works and the .env variables it needs without updating the README.
I switched from SERVICES and INFRASTRUCTURE variables to ACTIVE_SERVICES and SAVE_BACKUP listing all the services you want to run and a subset of services you want to stop before doing a backup, respectively. 

You can see details in [this commit](https://github.com/SimonHaas/homeserver/commit/ac3a409044648987518ceb9b9a380ca187925388)

**Comment by SimonHaas** [comment]
By the way: 

The backup.sh script is not yet generic enough to work for everyone. It is still pretty much tailor made for me with my specific paths for source and backup.

**Comment by nomadism19** [comment]
Yup, that was the problem! Changed the variable to ACTIVE_SERVICES and voila, activated without any issue. Thanks. I have been making modifications for my own setup and yes I came across your borg backup script in German. Your backup directories are also still present in the Homepage compose file.
